services:
  docs:
    init: true
    image: redocly/redoc
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    environment:
      SPEC_URL: openapi/openapi.yaml
    ports:
      - "127.0.0.1:8081:80"

  workspace:
    init: true
    build:
      context: .
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
      - dist:/workspace/dist
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  dist: {}
  node_modules: {}
